name: justfiber_installer_app
description: Modern installer field app for JustFiber.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  mobile_scanner: ^7.1.3
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.3
  google_fonts: ^6.2.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_splash.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon_splash.png"
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
